version: "3.3"
services:
  streamlit:
    build: .
    command: "streamlit run app.py"
    ports:
      - "8501:8501"
    #volumes:
    #  - mlruns:/mlruns  # app writes into mlruns
  mlflow:
    build: .
    command: "mlflow server --host 127.0.0.1"
    ports:
      - "5000:5000"
    #volumes:
    #  - mlruns:/mlruns  # mlflow reads from mlruns

#volumes:
#  mlruns:

#services:
#  streamlit:
#    build:             # <-- This block builds an image with the code
#      command: "streamlit run app.py"
#      ports:
#        - "8501:8501"
#    # volumes:         # <-- So delete this block
#    #   - ./client:/usr/src/client:ro
#    #   - /usr/src/client/node_modules
#  mlflow:
#    build: 
#      context: ./
#      dockerfile: ./server/Dockerfile
#    # volumes:         # <-- And this one
#    #   - ./server:/usr/src/server:ro
#    #   - /usr/src/server/node_modules